name: lints
version: 3.0.0
description: >
  Official Dart lint rules. Defines the 'core' and 'recommended' set of lints
  suggested by the Dart team.
repository: https://github.com/dart-lang/lints

topics:
  - analysis
  - lints

environment:
  sdk: ^3.0.0

# NOTE: Code is not allowed in this package - do not add dependencies.
# dependencies:

dev_dependencies:
  collection: ^1.17.0
  http: ^1.0.0
  path: ^1.8.0
  yaml: ^3.1.0
